### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by farski** [imsky/git-fresh#23]
Would be super nice if this were available through Homebrew

**Comment by imsky** [comment]
ok will add ASAP

edit: might need some time before this repo meets homebrew acceptance criteria

**Comment by shkm** [comment]
+1 on this, would love homebrew.

**Comment by selfagency** [comment]
+1

**Comment by imsky** [comment]
this is now in progress

**Comment by imsky** [comment]
`brew update && brew install git-fresh`

this is now done :ok_hand:

**Comment by farski** [comment]
:clap:
