### ISSUE TITLE
Add option to remove only local stale branches

### ISSUE THREAD

**Issue by nesl247** [imsky/git-fresh#50]
It would be nice to be able to remove stale branches, but only the local ones. My use case is I'm working in a large team, and there are a bunch of branches that while stale upstream, are not necessarily ones we want to remove without a discussion.

**Comment by imsky** [comment]
good idea, will add that asap

**Comment by imsky** [comment]
This has been implemented as the `-l` flag - let me know if there are any issues using it.

**Comment by nesl247** [comment]
Thanks so much!
