### ISSUE TITLE
Running `git fresh -f` can leave untracked files

### ISSUE THREAD

**Issue by ejlangev** [imsky/git-fresh#60]
Given I run `git fresh -f` from a branch that has been merged it can leave untracked files in the working tree in some cases if they were deleted on the master branch in between the local version of master `git fresh -f` will sync and the yet to be synced remote version.  This causes me to have to `rm` the untracked files afterwards which is easy to forget and might be swept up into a commit by an unsuspecting git noob.

**Comment by imsky** [comment]
can't replicate this with deleted files on a master branch - git-fresh's automatic rebase takes care of it.

can you post a reproducible test case?

**Comment by imsky** [comment]
following up. can you post a script that uses a local remote and replicates this issue?

**Comment by ejlangev** [comment]
Yes, I've been lazy about doing it but I'll take care of it shortly.

**Comment by ejlangev** [comment]
Can't seem to reproduce this.  Must be some other state required to get it to happen.  I've only had it happen 2 or 3 times.  Will close for now and re-open if I find a way to reproduce.
