### ISSUE TITLE
git fresh -f error

### ISSUE THREAD

**Issue by markogresak** [imsky/git-fresh#71]
When running `git fresh -f`, I always get this error:

```
[git-fresh] Error on line 173: echo -n $LOCAL_STALE | tr " " "\0" | xargs -0 git branch -d 2> /dev/null
```

According to `brew upgrade git-fresh`, I'm using version 1.6.2.

**Comment by imsky** [comment]
could you remove the `2> /dev/null` on L173, run the command again, and paste the output? thanks

**Comment by markogresak** [comment]
I've figured it out. The issue was in one of the repos with one stale branch which was merged into master, but `git branch -d` said that it's not fully merged. I've manually removed the branch using `git branch -D` and ran `git fresh -f` again, it worked this time. 
I wouldn't say this is a bug, this edge case is user's fault and they should figure out what's going on that's making git think the branch is not fully merged before they remove said branch.

**Comment by imsky** [comment]
thanks for letting me know - i'll enable error output
