### ISSUE TITLE
git fresh alters the last branch

### ISSUE THREAD

**Issue by raszi** [imsky/git-fresh#72]
``` bash
git checkout -b something
git checkout master
git fresh
git checkout -
```

Unfortunately this will stay in the master instead of the something branch.

**Comment by imsky** [comment]
hmm this bug happened before. what version are you using?

**Comment by raszi** [comment]
1.6.2 from homebrew

**Comment by raszi** [comment]
I can see that is not the most up-to-date version, I should open an issue for homebrew.

**Comment by raszi** [comment]
Well, the homebrew formula uses the archive tarballs, see it [here](https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/git-fresh.rb).

Could you please tag the new version(s)?

**Comment by imsky** [comment]
the new version isn't quite ready yet.

can you create a test case for this? a shell script that `git init`s and uses git fresh would be useful.

**Comment by raszi** [comment]
Would this work?

https://gist.github.com/raszi/6d1a7700d7612c7e6d2b81cbce806e81

**Comment by imsky** [comment]
seems good enough, i'll test it out asap

**Comment by imsky** [comment]
I can replicate the issue, working on a fix.

**Comment by imsky** [comment]
this is now fixed
