### ISSUE TITLE
Whitelist branches

### ISSUE THREAD

**Issue by raszi** [imsky/git-fresh#74]
I like the `-f` option but it deletes all the remote branches without asking. It would be great to have some whitelisting so I could keep the `production` branch but still use the `-f` option.

**Comment by imsky** [comment]
good idea, will look into it

**Comment by imsky** [comment]
this is now implemented @raszi

**Comment by Anahkiasen** [comment]
How do you use this? I can't find any flag or something that matches this feature, would like to use it to prevent `git-fresh` from always deleting `master` when working on `develop` which breaks git-flow

**Comment by imsky** [comment]
@Anahkiasen add the branches you want to keep to `.freshignore` in the root of the repo

**Comment by Anahkiasen** [comment]
Does it also work with a global `~/.freshignore`? It's just to always whitelist master no matter the repository in my case

**Comment by imsky** [comment]
@Anahkiasen that's a good point, there is no global .freshignore support yet. i'll add an issue for it. for now you'll have to specify a .freshignore for each repo you want to whitelist master in.
