### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [imsky/git-fresh#81]
Based on https://github.com/imsky/git-fresh/releases/latest it's not clear to me whether 1.3.0 or 1.10.0 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by imsky** [comment]
1.10.0 is the latest, thanks for making the update.

**Comment by ilovezfs** [comment]
@imsky no problem. Do you mind deleting the explicit release for 1.3.0 so that https://github.com/imsky/git-fresh/releases/latest doesn't point to the wrong thing?

The delete button should be on this page: https://github.com/imsky/git-fresh/releases/tag/v1.3.0

**Comment by imsky** [comment]
yeah i noticed it yesterday, will do

**Comment by ilovezfs** [comment]
Thanks!
