### ISSUE TITLE
Needs help docs

### ISSUE THREAD

**Issue by dan-blanchard** [imsky/git-fresh#82]
I love `git fresh`. I use it constantly, but the only way I notice flags that I don't use already is by looking at this repo directly. It would be amazing if there was a man page for it so that `git help fresh` or `git fresh --help` worked.

**Comment by imsky** [comment]
good idea @dan-blanchard. you can run `git fresh -?` to see documentation currently.

i'll consider man page and/or a `--help` flag.

**Comment by imsky** [comment]
@dan-blanchard there is now a `--help` flag and a man page

will be released shortly
