### ISSUE TITLE
Poor error message with `git fresh -f` in a repo with github protected branch

### ISSUE THREAD

**Issue by fzembow** [imsky/git-fresh#89]
Hi!

We have a github [protected branch](https://help.github.com/articles/about-protected-branches/) that cannot be deleted.

I know I can add it to `.freshignore` but would be nice if the error were not the following but rather something more informative if possible:

```
git fresh -f
Fetching origin
[git-fresh] Error on line 258: fi
```

Cheers,
f

**Comment by imsky** [comment]
yeah i agree, i've run into similar opaque errors before. will fix soon

**Comment by imsky** [comment]
this is now implemented. the error message should read:

```
[git-fresh] Error on line 269: could not delete stale remote branches: protected
```

will be released shortly

cc @fzembow

**Comment by fzembow** [comment]
looks good thanks @imsky  :)
