### ISSUE TITLE
Change directory to repo root before making changes

### ISSUE THREAD

**Issue by imsky** [imsky/git-fresh#91]
if the user is in a directory on a branch that doesn't exist on master, they'll get a "no such file or directory" error while getting current working directory in the script.

the way this could work is:

* detect repo root
* save current dir
* change dir to repo root
* run fresh operations
* change dir to previous current dir (if it exists)

**Comment by imsky** [comment]
cc @MichaelSelberg

**Comment by MichaelSelberg** [comment]
Thanks @imsky
